apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: remove
spec:
  description: This task will clean up a workspace by deleting all the files.
  workspaces:
    - name: source
  steps:
    - name: remove
      image: alpine:3
      env:
        - name: WORKSPACE_SOURCE_PATH
          value: $(workspaces.source.path)
      workingDir: $(workspaces.source.path)
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      script: |
        #!/usr/bin/env sh
            set -eu
            echo "Eliminando todos los archivos de ${WORKSPACE_SOURCE_PATH} ..."
            # Elimina cualquier contenido existente del directorio si existe.
            #
            # No usamos solo "rm -rf ${WORKSPACE_SOURCE_PATH}" porque ${WORKSPACE_SOURCE_PATH} podría ser "/"
            # o la raíz de un volumen montado.
            if [ -d "${WORKSPACE_SOURCE_PATH}" ] ; then
              # Elimina archivos y directorios no ocultos
              rm -rf "${WORKSPACE_SOURCE_PATH:?}"/*
              # Elimina archivos y directorios que comienzan con . pero excluyendo ..
              rm -rf "${WORKSPACE_SOURCE_PATH}"/.[!.]*
              # Elimina archivos y directorios que comienzan con .. más cualquier otro carácter
              rm -rf "${WORKSPACE_SOURCE_PATH}"/..?*
            fi
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose
spec:
  description: Tarea de prueba.
  workspaces:
    - name: source
  params:
    - name: args
      description:  Argumentos a pasar a nose
      type: string
      default:  "-v"
  steps:
    - name: remove
      image: alpine:3
      env:
        - name: WORKSPACE_SOURCE_PATH
          value: $(workspaces.source.path)
      workingDir: $(workspaces.source.path)
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      script: |
        #!/usr/bin/env sh
        set -e
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
        nosetests $(params.args)